In [ ]:
#NumPy, we can create arrays, work with matrices, and perform mathematical operations very efficiently.


In [1]:
!pip install numpy


In [3]:
import numpy as np
a = np.array([1, 2, 3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
print(a.shape)

(3,)


In [ ]:
a1 = np.array([1, 2, 3])
a1.reshape(1,3) #1 row and 5 columns


array([[1, 2, 3]])

In [4]:
a1=np.array([[1,2,3,4,5]])
a1.shape

(1, 5)

In [ ]:
#2-d array
a1=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(a1)
print(a1.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [ ]:
np.arange(0,10,2).reshape(5,1) # 5 rows and 1 column

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [6]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [2]:
#identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#attributes of numPy
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int64
8


In [6]:
#numpy vectorized operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

#element wise addition
print("addition:",arr1+arr2)

#element wise subtraction
print("subtraction:",arr2-arr1)


addition: [11 22 33 44 55]
subtraction: [ 9 18 27 36 45]


In [8]:
#universal function
arr=np.array([2,3,4,5,6])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [ ]:
#array slicing and indexing
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array:\n",arr)
arr[0][0]
# arr[1:]   ##1index row se start krke end tk
arr[2:]   ##2 index row se start krke end tk

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[ 9, 10, 11, 12]])

In [12]:
arr[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
arr[1:,2:]  #1 last elements+2nd k last elements
 

array([[ 7,  8],
       [11, 12]])

In [16]:
print(arr[0:2,2:])

[[3 4]
 [7 8]]


In [18]:
#modify array elements
arr[0][0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [20]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [21]:
#  Statistical Operations and Normalization
#to have a mean of 0 and standard deviation of 1
data = np.array([1, 2, 3, 4, 5])
mean = np.mean(data)
std = np.std(data)
normalized_data = (data - mean) / std
print(normalized_data)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [4]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

5.5
5.5
2.8722813232690143
8.25


In [22]:
#LOGICAL OPERATION
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(data > 5)
print(data[data > 5])
print(data[(data >= 5) & (data <= 8)])

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[5 6 7 8]
